#!/bin/sh

ct=`which ctags-exuberant` \
|| echo 'NOTE: sudo apt install exuberant-ctags for ctag file' >&2

cd `dirname $0`

csources="
	timelock.c
	third_party/libbtc/src/base58.c
	third_party/libbtc/src/trezor-crypto/sha2.c
	third_party/libbtc/src/trezor-crypto/memzero.c
	third_party/libbtc/src/chainparams.c
	third_party/libbtc/src/ecc_key.c
	third_party/libbtc/src/ecc_libsecp256k1.c
	third_party/libbtc/src/memory.c
	third_party/libbtc/src/secp256k1/src/secp256k1.c
	third_party/libbtc/src/random.c
	third_party/libbtc/src/trezor-crypto/base58.c
	third_party/libbtc/src/trezor-crypto/segwit_addr.c
	third_party/libbtc/src/ripemd160.c
	third_party/libbtc/src/utils.c
	third_party/libbtc/src/cstr.c
	third_party/libbtc/src/script.c
	third_party/libbtc/src/trezor-crypto/hasher.c
	third_party/libbtc/src/trezor-crypto/ripemd160.c
	third_party/libbtc/src/serialize.c
	third_party/libbtc/src/vector.c
	third_party/libbtc/src/trezor-crypto/blake256.c
	third_party/libbtc/src/trezor-crypto/sha3.c
	third_party/libbtc/src/trezor-crypto/groestl.c
	third_party/libbtc/src/trezor-crypto/blake2b.c
"

(
echo $csources
find . -name '*.h'
) > /tmp/tagfiles.$$

$ct --format=1 `cat /tmp/tagfiles.$$`

gcc	-I third_party/libbtc/include 			\
	-I third_party/libbtc/src/secp256k1			\
	-o timelock					\
	-D ECMULT_WINDOW_SIZE=15			\
	-D ECMULT_GEN_PREC_BITS=4			\
	-D RANDOM_DEVICE=\"/dev/random\"		\
	-D ENABLE_MODULE_RECOVERY=1			\
	$csources -lm
